# Replace these placeholder values with your actual API keys
# For local development: Use your actual API keys
# For deployment: Set these values in your deployment platform's environment variables
OPENWEATHER_API_KEY = "012ef47845678a992ebd6f731235e756"
GEMINI_API_KEY = "AIzaSyArHVLej4ZiHLhN9CdeBtfMOGFfTTpeNkM"
